todo_project/todo_app/urls.py
from . import views
from django.conf.urls.static import static

from django.urls import path
app_name='todo'

urlpatterns = [


     path('', views.home, name='home'),
     path('delete/<int:taskid>/', views.delete, name='delete'),
     path('update/<int:id>/', views.update, name='update'),
     path('cbvhome/', views.todolistview.as_view(), name='cbvhome'),
     path('cbvdetail/<int:pk>', views.todoDetailview.as_view(), name='cbvdetail'),
     path('cbvupdate/<int:pk>', views.todoUpdateview.as_view(), name='cbvupdate'),
     path('cbvdelete/<int:pk>', views.todoDeleteview.as_view(), name='cbvdelete'),
 ]

todo_project/todo_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from todo_project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_app.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo_project/todo_app/models.py
from django.db import models


# Create your models here.


class todo(models.Model):
    task = models.CharField(max_length=250)
    priority = models.IntegerField()
    date=models.DateField()

    def __str__(self):
        return self.task

todo_project/todo_app/forms.py
from django import forms

from .models import todo


class todo_forms(forms.ModelForm):
    class Meta:
        model = todo
        fields = ['task', 'priority', 'date']

todo_project/todo_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .forms import todo_forms
from .models import todo
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView


class todolistview(ListView):
    model = todo
    template_name = 'home.html'
    context_object_name = "temp"

class todoDetailview(DetailView):
    model = todo
    template_name = 'detail.html'
    context_object_name = "task"




class todoUpdateview(UpdateView):
    model = todo
    template_name = 'edit.html'
    context_object_name = "task"
    fields=('task', 'priority', 'date')
    def get_success_url(self):
        return reverse_lazy('cbvdetail',kwargs= {'pk':self.object.id})

class todoDeleteview(DeleteView):
    model = todo
    template_name = 'delete.html'
    success_url = reverse_lazy('cbvhome')




def home(request):
    tasks=todo.objects.all()

    if request.method=='POST':
        name=request.POST.get('task','')
        priority=request.POST.get('priority','')
        date=request.POST.get('date','')
        task=todo(task=name,priority=priority,date=date)
        task.save()

    return render(request, 'home.html',{'temp':tasks})


def delete(request,taskid):
    task = todo.objects.get(id=taskid)
    if request.method=='POST':

        task.delete()
        return redirect('/')
    return render(request,'delete.html')

def update(request, id):
    idd = todo.objects.get(id=id)
    form = todo_forms(request.POST or None, request.FILES, instance=idd)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'update.html', {'form': form, 'idd': idd})

todo_project/todo_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

{% block content %}

{% endblock %}

</body>
</html>

todo_project/todo_app/templates/delete.html
{% extends 'base.html' %}

{% block content %}

<form method="post">
  {% csrf_token %}
  <label>Are You sure that you are done this task..?</label>
  <input type="submit" class="btn btn-success">
</form>

{% endblock %}

todo_project/todo_app/templates/detail.html
{% extends 'base.html' %}

{% block content %}

 <div class=" shadow card">
                    <div class="card-body">
                        <h5 class="card-title" style="color:black;">{{task.task}}</h5>
                        <p>{{task.priority}}</p>
                        <p><b>{{task.date}}</b></p>
                                  <a href="{% url 'todo:delete' task.id %}" class="btn btn-primary">Done</a>
                                  <a href="{% url 'todo:cbvupdate' task.id %}" class="btn btn-primary">Update</a>
                </div>
            </div>


{% endblock %}

todo_project/todo_app/templates/edit.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>TASK UPDATE</h1>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form method="post" class="shadow-lg p-3 mb-5 bg-white rounded">
              {% csrf_token %}
               {{form.as_p}}
                <div>
                    <input type="submit" class="btn btn-danger">
                </div>
                </form>

    </div>

</div>
</div>

{% endblock %}

todo_project/todo_app/templates/home.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>ToDo LisT</h1>
                </div>
            </div>
        </div>
    </div>
</div>




<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="post" class="shadow-lg p-3 mb-5 bg-white rounded">
              {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" name="task" placeholder="Enter the Task">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="priority" placeholder="Enter the priority">
                </div>
                <div class="form-group">
                    <input type="date" class="form-control" name="date" placeholder="Enter the date">
                </div>
                <div>
                    <input type="submit" class="btn btn-success">
                </div>
                </form>

    </div>

        <div class="col-md-6">
            <h4><b>Task To Be Completed</b></h4>
            {% for i in temp %}
            <div class=" shadow card">
                    <div class="card-body">
                        <a href="{% url 'todo:cbvdetail' i.id %}" class="card-title" style="color:black;">
                            <h5>{{i.task}}</h5>
                        </a>
                        <p>{{i.priority}}</p>
                        <p><b>{{i.date}}</b></p>
                                  <a href="{% url 'todo:delete' i.id %}" class="btn btn-primary">Done</a>
                                  <a href="{% url 'todo:update' i.id %}" class="btn btn-primary">Update</a>
                </div>
            </div>
            <br>
            {% endfor %}
        </div>
</div>
</div>
{% endblock %}

todo_project/todo_app/templates/update.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>UpDatE LisT</h1>
                </div>
            </div>
        </div>
    </div>
</div>




<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form method="post" class="shadow-lg p-3 mb-5 bg-white rounded">
              {% csrf_token %}
               {{form.as_p}}
                <div>
                    <input type="submit" class="btn btn-success">
                </div>
                </form>

    </div>

</div>
</div>
{% endblock %}